{{- if .Values.zoneLoadBalancer -}}
{{- range (.Values.zoneLoadBalancer | replace "\n" "," | replace " " "" | splitList ",") }}
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.kubernetes.io/ibm-load-balancer-cloud-provider-zone: {{ splitList "=" . | first }}
  name: {{ template "strongswan.fullname" $ }}-{{ splitList "=" . | first }}
  namespace: {{ template "strongswan.namespace" $ }}
  labels:
    app: {{ template "strongswan.name" $ }}
    chart: {{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "_" }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
spec:
  type: LoadBalancer
  loadBalancerIP: {{ splitList "=" . | last }}
{{- if $.Values.enableServiceSourceIP }}
  externalTrafficPolicy: "Local"
{{- end }}
  ports:
    - port: 500
      targetPort: 500
      protocol: UDP
      name: ike
    - port: 4500
      targetPort: 4500
      protocol: UDP
      name: ike-nat
  selector:
    app: {{ template "strongswan.name" $ }}
    release: {{ $.Release.Name }}
---
{{- end }}
{{- end -}}
